### ISSUE TITLE
bug mac上无法使用

### ISSUE THREAD

**Issue by zifeicsy** [bilibili-ayang/bob-plugin-free-baidu-translate#1]
请求翻译接口失败,请检查网络

提示上面的错误
![github](https://github.com/ayangweb/bob-plugin-free-baidu-translate/assets/63597902/87fcd3df-7871-4392-a8ff-8653385c6339)

**Comment by ayangweb** [comment]
> 请求翻译接口失败,请检查网络
> 
> 提示上面的错误 ![github](https://private-user-images.githubusercontent.com/63597902/293297682-87fcd3df-7871-4392-a8ff-8653385c6339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTU3MDcsIm5iZiI6MTcwMzgxNTQwNywicGF0aCI6Ii82MzU5NzkwMi8yOTMyOTc2ODItODdmY2QzZGYtNzg3MS00MzkyLWE4ZmYtODY1MzM4NWM2MzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAyMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTQ4ZjJkZmZmZDRmZDliZDA1NGFjMjI4NmQzZjE1NGNjMThmMzdiZTk5OWExOTU1YzhiMTY3MTk5MTQ2M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t7sW6BgOq6NnkyWC09SZ50ho6Kr384WA627AjkMlEmA)

你反馈的这个插件不是我写的哦，我的插件名称没有 Free，使用也正常哈！

<img width="430" alt="image" src="https://github.com/ayangweb/bob-plugin-free-baidu-translate/assets/75017711/d4b19387-275a-459a-a9c1-449c4bc81ae9">
